== 9. RELATED PM² PLANS
[discrete]
==== Project Handbook
The Project Handbook establishes the high-level approach for implementing the project goals, which includes required documentation, standards to be considered and the high-level summary of the risk management approach and escalation process. The location of this artefact is referred in the Appendix 1.
[discrete]
==== Communications Management Plan
The Communications Management Plan helps to ensure that all project stakeholders have the information they need to perform their roles throughout the project. It defines and documents the communication items content, format, frequency, the audience and expected results. The location of this artefact is referred in the Appendix 1.
[discrete]
==== Issue Management
The management of issues is described in the Issue Management Plan. This artefact defines how issues are identified, evaluated, and assigned for resolution. Issue management supports the resolution of issues after risks occur. The location of this artefact is referred in the Appendix 1.

