=== Risk Log

[cols=","]
|===
2+h| *Risk Identification and Description*

| ID |
The risk identifier.

| Category |
Risk category related to the area affected by the risk (e.g. business, IT, people & organisation, external or legal).

| Title |
A short title for the risk.

| Description |
A structured formulation of the opportunity or threat in the form of (route) Cause – Risk –Effect, along with potential risk inter-dependencies.

| Status |
The risk status can be any of the following:

*Proposed:* This is the initial status.
Use this while the risk is still being specified.

*Assessing:* Use this status to initiate an assessment.

*Waiting for Approval:* Use this to request approval.
Before applying this status, make sure the assessment is complete and the estimates are reliable.

*Approved:* This status is set once the risk possibility has been accepted.

*Rejected:* This status is set if the risk was rejected as not relevant.

*Closed:* This status is set once the risk has been managed (e.g. mitigation

| Identified by |
The person who identified the risk.

| Identification date |
The date on which the risk was identified.

2+h| *Risk Assessment*

| Likelihood (L) |
A numerical value denoting the estimate of the probability that the risk will occur.
The possible values are:

*5=Very high, 4=High, 3=Medium, 2=Low, 1=Very low*

| Impact (I) |
A numerical value denoting the severity of the risk’s impact (should it occur). The possible values are:

*5=Very high, 4=High, 3=Medium, 2=Low, 1=Very low*

| Risk Level (RL) |
The risk level is the product of the likelihood and impact (*RL=L*I*).

| Risk owner |
The person accountable for managing and monitoring the risk.

| Escalation |
Whether or not the risk is to be escalated to the Directing or Steering Layers (*Yes* or *No)*.

2+h| *Risk Response*

| Risk response Strategy |
Strategies for negative risks (threats): *Avoid, Reduce, Accept, Transfer/Share* Strategies for positive risks (opportunities):

*-Exploit, Enhance, Accept, Share*

| Action details (effort & responsible) |
Description of the action(s) to be taken, including its objective, scope, deliverables, and the person responsible and estimated effort needed.

| Target date |
The date on which the action is expected to be implemented.

| Traceability/Comments |
The ID(s) of the tasks (in the Project Work Plan) that implement the risk response actions, and/or the IDs of related changes, issues or decisions (log entries). Also include any additional information/comments related to the risk.
|===
