
=== Personal and Professional Virtues

Virtues are strengths (or excellence) of the person who possesses them and refer to the ideal management of our attitude, behaviour and actions that drive personal and professional performance.
Virtues are expressed in a _specific context_ as the healthy mean between the extremes of excess and deficiency, which, however, is not universal, but subjective, and as such will vary between individuals and their respective circumstances . This healthy mean should be determined by good judgment.

Virtues are developed through practice.
Their application helps us discover the right principles of conduct, to know what we ought to do in a given situation.
Acting in a virtuous way enables us to raise the effectiveness and efficiency of our performance as a means to serve our personal, professional, as well as our higher and more inclusive goals.

The virtue of *prudence (practical wisdom)* refers to our ability to carefully consider how we can achieve our goal.
Prudence is characterised as an executive disposition because its outcome is something to be executed.
It can be examined on two levels: the level of purpose (our ability to set worthy goals) and the level of deliberation (our ability to carefully consider the course and the means of our actions so as to achieve the desired goals).

*Judgment* refers to our ability to assess what is true and what is not.
Judgment forms our perception about things around us.
Therefore, it strongly affects our prudence, which in turn determines our actions.
When there is a deficiency in our Judgment (e.g. due to emotional factors or past experiences), we may consider as true something that is not and vice-versa (e.g. consider an act as fair when it is unfair).

It is through intuitive insight that the mind grasps the principles of conduct that may point the way toward success and happiness.
The virtue of *insightfulness* refers to our ability to perceive things correctly, to examine circumstances accurately, to understand the relationships between things, to analyse and synthesise.
It determines our capacity to learn or know what is the right thing to do and what is not, and to transfer this knowledge to various contexts in order to contribute to our wellbeing.

The virtue of *courage* refers to the management of risk taking and is described as the productive mean between _cowardice_ (a deficiency) and _audacity_ or fearlessness (an excess). A courageous person pursues (not necessarily without fear) the right goals, for the right reasons, in the right way, at the right time and for the right amount of time.
Therefore, a person who is courageous acts and endures whatever is logically required for the attainment of a worthy goal.
Courage (which always involves a risk) is a necessary means for the further development of one’s capacities.

The virtue of *honour* refers to our disposition to seek honours and rewards from others.
This virtue is defined as the mean between _lack of ambition_ (seeking less honours and rewards than are deserved or having no desire for honours) and _over-ambitiousness_ (an excessive desire for honours or seeking more honours and rewards than are deserved).

*Honesty* refers to our ability to tell the truth about ourselves and demonstrate to others who we really are, without denying or exaggerating our qualities.
This virtue is the mean between _self-deprecation_ (deficiency) and _boastfulness_ (excess).

The virtue of *fairness* (or Justice) in general is attained through the application of all other virtues.
However, there is a *particular* type of *fairness* that refers to our disposition to fairly distribute benefits and damages to those who deserve them, either between others and ourselves or amongst others.
Fairness is the mother of all virtues, and for one to be truly fair all virtues must be fully developed _(“Fairness is superior to all virtues and excellent” – Aristotle)._

The virtue of *generosity* refers to the management of things that have value (e.g. time, money, knowledge, information and other assets). It is defined as the productive mean between _stinginess_ (deficiency) and _wastefulness_ (excess). Generosity ensures that the valuable assets we possess, such as our knowledge, are shared with the right person, at the right time, in the right quantity and in the right way, so as to be used productively.
Generosity is determined not only by our willingness and ability to give (e.g. to use and share our knowledge), but also by whether our giving is in harmony with the long-term interests of the people involved, and in accordance to the other moral virtues.
One should follow the guidance of reason, as generosity is something that needs to be exercised with wisdom if it is to promote one’s own good and that of others.

The virtue of *friendliness* refers to the management of our amicability in our interactions with others.
It is defined as the mean between _rudeness_ (deficiency) and _obsequiousness_ (excess). A rude person enjoys conflict, without taking into consideration whether it displeases or embarrasses others, whereas an obsequious person demonstrates servitude and is mostly interested in being likeable to others, avoiding conflict even at great personal cost.

The virtue of *humour* is described as the mean between _boorishness_ (deficiency) and _buffoonery_ (excess) The boorish person does not enjoy humour, might even be unduly upset or annoyed by it.
On the other hand, the buffoon is someone who enjoys humour in excess, expresses it in an unproductive way, with inappropriate timing or frequency, possibly causing annoyance to others.

The virtue of *calmness* refers to the management of anger.
It is the mean between _spiritlessness_ (deficiency) and _irritability_ (excess). Spiritlessness refers to the lack of anger, while irritability refers to the excess of anger in its duration, intensity and frequency.
The calm person desires to remain calm and not get carried away by passion or rage, but to always act within reasonable limits.

The virtue of *temperance* refers to the management of our desires and is the mean between _insensibility_ (deficiency) and _intemperance_ (excess). A temperate person is one who desires moderately and reasonably all those pleasures that promote health and wellness.

The virtue of *magnificence* is similar to generosity, but it refers to the management of large assets.
It is defined as the mean between _paltriness_ (deficiency) and _vulgarity_ (excess). Paltriness prevails when someone contributes to an important cause with a miserly disposition.
On the contrary, vulgarity is displayed when someone contributes excessively, much more than is required or expected.

The virtue of *magnanimity* is similar to honour, but it refers to the management of high honours and rewards.
It is defined as the mean between _meekness_ (deficiency) and _vanity_ (excess). A meek person believes that they do not deserve great honours when they actually do deserve them, whereas a vain person believes that they deserve great honours when they actually do not deserve them.
The magnanimous (magnum=great) consider they deserve the greatest goods (wealth, influence, prestige, distinctions, etc.) when they do indeed deserve them.

All virtues are required for the application of professional competences, however, the intellectual virtues of judgment, prudence and insightfulness need to be transversally applied for their development.
The following table shows the strongest relations of moral virtues to key professional competencies.


[cols="1,2",options="header"]
|===
| Competence | Key Virtues

| Leadership
| All

| Relationships and engagement
| Fairness, Friendliness, Generosity, Honesty, Humour, Temperance


| Self-reflection and-self management
| Calmness, Courage, Friendliness, Honesty, Honour, Temperance

| Change and transformation
| Calmness, Courage, Friendliness, Generosity

| Personal communication
| Calmness, Friendliness, Generosity, Humour

| Resourcefulness
| Fairness, Friendliness, Generosity, Honesty, Honour

| Results orientation
| Honour, Generosity, Magnanimity, Magnificence

| Teamwork
| Calmness, Courage, Fairness, Friendliness, Generosity, Honour, Magnificence

| Negotiation
| Courage, Fairness, Friendliness, Generosity, Honesty, Honour

| Conflict and crisis management
| Calmness, Fairness, Friendliness, Generosity

| Personal integrity and reliability
| Calmness, Courage, Fairness, Friendliness, Honour, Temperance

| Culture and values management
| All virtues
|===
