=== PM² Code of Professional Conduct

Many organisations provide a code of ethics and conduct that members are required to respect.
The purpose is to help people navigate through the complexities of professional reality and remind them which attitudes and behaviours are aligned with a commonly accepted set of professional values.

Conduct means personal behaviour based on moral principles.
Professionalism is the skill, good judgment, and polite behaviour that is expected from a person who is trained to do a job well.
This section provides a useful reminder of the key principles that PM² practitioners (and project team members) should be aware of and respect.

* *INDEPENDENCE:* staff conduct, and decision-making should be determined by the need to serve the common good and public interest, and never by any other interests whether private or as a result of, for example, political pressure.
* *IMPARTIALITY:* staff members should be unbiased in any decisions they are called upon to make.
* *OBJECTIVITY:* any conclusions drawn by staff as part of the project work should be balanced and based on a thorough analysis of the facts and legal background.
* *LOYALTY*: loyalty towards the organisation is essential for maintaining its independence and achieving its objectives.
It is also necessary for the functioning of each service.


Putting these principles into practice requires:

* *CIRCUMSPECTION*: which is about stopping and reflecting on the possible consequences and implications of potential actions, showing a degree of moderation and a sense of proportion and propriety.
* *RESPONSIBILITY*: which is about carrying out those tasks entrusted to you as dutifully as possible and looking for solutions when difficulties are encountered.
It is also important to know and respect the legal obligations and administrative rules and procedures in force.

The key principles can be summarised as *INTEGRITY*, which means consistently adhering to ethical principles and making sound decisions based on them.

In addition to the aforementioned code of ethics, every practitioner of the PM² Project Management Methodology should act based on the following values:

* *LAWFULNESS* and *ACCOUNTABILITY*: act in accordance with the law and hold yourself accountable for decisions and acts.
* *FAIRNESS*: fairness is our duty to make decisions impartially and objectively, and free from self- interest, prejudice and favouritism.
* *NON-DISCRIMINATION* and *EQUAL TREATMENT*: respect the principle of non-discrimination and, in particular, guarantee equal treatment for members of the public irrespective of nationality, gender, racial or ethnic origin, religion or beliefs, disability, age or sexual orientation.
* *PROPORTIONALITY* and *CONSISTENCY*: ensure that measures taken are proportional to the aim pursued and be consistent in your behaviour.
* *RESPECT* and *LEADERSHIP*: exercise the power of your position with responsibility and promote ethical principles and professional conduct by leadership and example.
* *HONESTY* and *OPENESS*: declare any private interests and openly provide reasons for any decision.
* *TEAMWORK* and *CONFLICT RESOLUTON*: work together to achieve common goals by finding solutions through better mutual understanding.
* *POLITENESS* and *CLEAR COMMUNICATION*: engage colleagues by showing respect and encouraging efficiency through clarity of instructions.
