== 11. RELATED PM² PLANS
[discrete]
==== Project Handbook
The Project Handbook establishes the high-level approach for implementing the project goals, which includes required documentation, standards to be considered and the high level summary of the change management approach and escalation process. The location of this artefact is found in the Appendix 1.
[discrete]
==== Communications Management Plan
The Communications Management Plan helps to ensure that all project stakeholders have the information they need to perform their roles throughout the project. It defines and documents the communication items content, format, frequency, the audience and expected results. It describes the Project Status meeting where change requests are discussed. The location of this artefact is found in the Appendix 1.
[discrete]
==== Quality Management Plan
The quality management (quality requirements, approach, process and responsibilities, and quality assurance and control activities) is described in the Quality Management Plan, as well as the project configuration procedure for deliverables and artefacts changes. The location of this artefact is found in the Appendix 1.
[discrete]
==== Issue Management
The management of issues is described in the Issues Management Plan. This artefact defines how issues are identified, evaluated, and assigned for resolution. Issue management supports the resolution of issues that may involve change management process. The location of this artefact is found in the Appendix 1


